### PR TITLE
Update OpenZeppelin account artifacts to v0.2.1

### LINKED ISSUE #161: OpenZeppeling 0.2.0 account contract have an issue with signature verification.
I have tried running the `oz-account-test.ts` test of `starknet-plugin-exaple` and ran into the following issue:
```

  2) OpenZeppelin account
       should handle multiple invokes through an account:
     Error: Transaction rejected. Error message:

Error at pc=0:133:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:746)
Unknown location (pc=0:682)
Error message: Account: invalid signature
Unknown location (pc=0:347)
Unknown location (pc=0:321)

Traceback (most recent call last):
  File "<hint14>", line 1, in <module>
  File "/app/src/starkware/starknet/services/batcher/starknet_batcher_venv-site/starkware/cairo/lang/builtins/signature/signature_builtin_runner.py", line 94, in add_signature
    ), f"Signature hint must point to the signature builtin segment, not {addr}."
AssertionError: Signature hint must point to the signature builtin segment, not 14:0.
```

The cause is probably this issue [#378](https://github.com/OpenZeppelin/cairo-contracts/pull/387#issuecomment-1183208148) of OpenZeppelin with contracts of version 0.2.0 on Goerli testnet.

### PR DESCRIPTION
**Pull request by amanusk**
Updates OpenZeppelin account version to 0.2.1
Fixes #161

## Usage related changes

-   Use v0.2.1 of OpenZeppelin accounts

## Development related changes

-   Running `npx hardhat test --no-compile test/oz-account-test.ts` should now pass with both devnet and alpha-goerli

## Checklist:

-   [ ] Formatted the code
-   [ ] No linter errors
-   [ ] Tried to avoid introducing linter warnings
-   [ ] Performed a self-review of the code
-   [ ] Rebased to the last commit of the target branch (or merged it into my branch)
-   [ ] Documented the changes
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.sh`)
-   [ ] Linked issues which this PR resolves
-   [ ] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
    -   < EXAMPLE_REPO_PR_URL > 
    -   [ ] Modified `test.sh` to use my example repo branch
    -   [ ] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

### CODE REVIEW

**Comment by FabijanC** [comment]
The ABI is the same as it was for 0.2.0?

**Review by FabijanC — COMMENTED** [review]
I'll approve & merge this when you can confirm that you successfully ran `quick-test.ts` and `oz-account-test.ts` from `starknet-hardhat-example` with this new account artifact.

**Comment by amanusk** [comment]
Tests are passing, and also running `npm run test-general-tests` is passing

**Review by FabijanC — APPROVED** [review]

**Comment by martriay** [comment]
> Yes, the ABI is the same. Checked with diff..

Can confirm.

**Pull request merged**
